<div>
<p ><img  align="right" src="https://res.cloudinary.com/crunchbase-production/image/upload/c_lpad,h_256,w_256,f_auto,q_auto:eco,dpr_1/aj29iemt0ogdyrdlksd4" height="160px"></p>
</div>

<br>
<br>

# **01 - Criando Objetos com Pandas (DataFrame e Series)**

<br>
<br>

___

**Importação da Biblioteca**

*Exercício 1: Criação de uma Série*

- Importe a biblioteca pandas.
- Crie uma série chamada "idades" com os seguintes dados: [25, 30, 35, 40, 45].
- Imprima a série.

*Exercício 2: Criação de um DataFrame*

Importe a biblioteca pandas.
* Crie um DataFrame chamado "dados_alunos" com as colunas "Nome" e "Idade".
* Preencha o DataFrame com os seguintes dados:
* Nome: "Maria", "João", "Pedro", "Ana", "Luiz"
* Idade: 25, 30, 35, 40, 45.
* Imprima o DataFrame.

*Exercício 3: Acesso a Dados em uma Série*

- Importe a biblioteca pandas.
- Crie uma série chamada "notas" com os dados: [8.5, 9.0, 7.5, 10.0, 6.0].
- Acesse e imprima a nota do terceiro elemento da série.

*Exercício 4: Acesso a Dados em um DataFrame*

- Importe a biblioteca pandas.
- Utilize o DataFrame "dados_alunos" criado no exercício 2.
- Acesse e imprima a idade do aluno com nome "Ana".

<div>
<p ><img  align="right" src="https://res.cloudinary.com/crunchbase-production/image/upload/c_lpad,h_256,w_256,f_auto,q_auto:eco,dpr_1/aj29iemt0ogdyrdlksd4" height="160px"></p>
</div>

<br>
<br>

# **02 - Funções do Pandas - Parte I**

**Funções**
* **head**: Retorna as 5 primeiras linhas.
* **columns**: Os rótulos de coluna do DataFrame.
* **rename**: Altere os rótulos dos eixos.
* **index**: Obtém os índices (rótulos de linha) do DataFrame.
* **dtypes**: Retorna os tipos de dados presentes no DataFrame.
* **shape**: Retorna uma tupla representando a dimensionalidade do DataFrame.
* **info**: Imprime um resumo conciso de um DataFrame.
* **values**: Retorne uma representação Numpy do DataFrame.
<br>
<br>
___

**Importação da Biblioteca**

*Exercício 1: Utilizando a função head()*

- Importe a biblioteca pandas.
- Crie um DataFrame chamado "dados_alunos" com as colunas "Nome" e "Idade".
- Preencha o DataFrame com os seguintes dados:
- Nome: "Maria", "João", "Pedro", "Ana", "Luiz"
- Idade: 25, 30, 35, 40, 45.
- Use a função head() para imprimir as 2 primeiras linhas do DataFrame.

*Exercício 2: Utilizando a função columns*

- Utilize o DataFrame "dados_alunos" criado no exercício anterior.
- Use a função columns para obter os rótulos das colunas do DataFrame e imprima-os

*Exercício 3: Utilizando a função rename*

- Utilize o DataFrame "dados_alunos" criado no exercício 1.
- Utilize a função rename para renomear a coluna "Nome" para "Aluno" e a coluna "Idade" para "Idade (anos)".
- Imprima o DataFrame após a renomeação.

*Exercício 4: Utilizando a função index*

- Utilize o DataFrame "dados_alunos" após a renomeação no exercício anterior.
- Use a função index para obter os rótulos de linha (índices) do DataFrame e imprima-os.

*Exercício 5: Utilizando a função dtypes*

- Importe a biblioteca pandas.
- Crie um DataFrame chamado "dados_clientes" com as colunas "Nome", "Idade", "Email" e "Telefone".
- Preencha o DataFrame com dados fictícios.
- Use a função dtypes para obter os tipos de dados das colunas do DataFrame e imprima-os.

*Exercício 6: Utilizando a função shape*

- Utilize o DataFrame "dados_clientes" criado no exercício 5.
- Use a função shape para obter a dimensionalidade do DataFrame e imprima-a.

*Exercício 7: Utilizando a função info*

- Utilize o DataFrame "dados_clientes" criado no exercício 5.
- Use a função info para imprimir um resumo conciso do DataFrame, incluindo informações sobre tipos de dados e valores não nulos.

*Exercício 8: Utilizando a função values*

- Utilize o DataFrame "dados_clientes" criado no exercício 5.
- Use a função values para obter uma representação Numpy do DataFrame e imprima-a.

<div>
<p ><img  align="right" src="https://res.cloudinary.com/crunchbase-production/image/upload/c_lpad,h_256,w_256,f_auto,q_auto:eco,dpr_1/aj29iemt0ogdyrdlksd4" height="160px"></p>
</div>

<br>
<br>

# **03 - Funções do Pandas - Parte II**

**Funções**
* **reset_index**: Redefina os índices.
* **select_dtypes**: Retorna um subconjunto das colunas do DataFrame com base nos tipos de coluna.
* **drop**: Remove linhas ou colunas.
* **assign**: Atribue novas colunas a um DataFrame.
* **astype**: Converta um objeto pandas para um tipo especificado.
* **value_counts**: Retorna uma série contendo contagens de linhas exclusivas no DataFrame.
<br>
<br>
___

**Importação da Biblioteca**

*Exercício 1: Utilizando a função reset_index()*

- Importe a biblioteca pandas.
- Crie um DataFrame chamado "dados_alunos" com as colunas "Aluno" e "Idade".
- Configure os índices para as letras "A", "B", "C" e "D".
- Use a função reset_index() para redefinir os índices e imprimir o DataFrame.

*Exercício 2: Utilizando a função select_dtypes()*

- Importe a biblioteca pandas.
- Crie um DataFrame chamado "dados" com colunas de diferentes tipos de dados, como inteiros, flutuantes e strings.
- Use a função select_dtypes() para selecionar apenas as colunas do tipo int64 e imprima o subconjunto do DataFrame.

*Exercício 3: Utilizando a função drop()*

- Utilize o DataFrame "dados_alunos" criado no exercício 1.
- Use a função drop() para remover a linha com índice "B" e imprima o DataFrame resultante.

*Exercício 4: Utilizando a função assign()*

- Importe a biblioteca pandas.
- Crie um DataFrame chamado "dados" com as colunas "Nome" e "Idade".
- Utilize a função assign() para adicionar uma nova coluna chamada "Sexo" ao DataFrame e preencha-a com os valores "F", "M" e "F".
* Imprima o DataFrame após a atribuição.

*Exercício 5: Utilizando a função astype()*

- Importe a biblioteca pandas.
- Crie um DataFrame chamado "dados" com uma coluna que contém números como strings.
- Use a função astype() para converter os valores da coluna em números inteiros.
- Imprima o DataFrame após a conversão.

*Exercício 6: Utilizando a função value_counts()*

- Importe a biblioteca pandas.
- Crie um DataFrame chamado "dados" com uma coluna que contém nomes de cores.
- Use a função value_counts() para contar as ocorrências únicas de cores no DataFrame e imprima a série resultante.

<div>
<p ><img  align="right" src="https://res.cloudinary.com/crunchbase-production/image/upload/c_lpad,h_256,w_256,f_auto,q_auto:eco,dpr_1/aj29iemt0ogdyrdlksd4" height="160px"></p>
</div>

<br>
<br>

# **04 - Importar e Exportar Arquivos com Pandas**
<br>
<br>

___

*Exercício 1: Coloque em prática o que você aprendeu*

Até agora utilizamos funções do pandas em bases públicas. Nesse exercício, convidamos você a encontrar alguma planilha ou arquivo CSV que você utiliza no seu trabalho para carregar no pandas (com o método read_csv ou read_excel) e aplicar as funções que aprendemos até agora, como value_counts, ou unique, etc para visualizar os resultados

<div>
<p ><img  align="right" src="https://res.cloudinary.com/crunchbase-production/image/upload/c_lpad,h_256,w_256,f_auto,q_auto:eco,dpr_1/aj29iemt0ogdyrdlksd4" height="160px"></p>
</div>

<br>
<br>

# **05 - Indexação e Seleção de Dados**

<br>
<br>

___

*Exercício 1: Utilizando a função loc para Selecionar Linhas por Rótulo*

- Importe a biblioteca pandas.
- Crie um DataFrame chamado "dados_alunos" com as colunas "Nome" e "Idade".
- Configure os índices para as letras "A", "B", "C" e "D".
- Utilize a função loc para selecionar e imprimir as informações do aluno com índice "B".

*Exercício 2: Utilizando a função iloc para Selecionar Linhas por Índice Numérico*

- Utilize o DataFrame "dados_alunos" criado no exercício 1.
- Use a função iloc para selecionar e imprimir as informações do aluno na segunda linha.

*Exercício 3: Utilizando a função loc para Selecionar Colunas por Rótulo*

- Utilize o DataFrame "dados_alunos" criado no exercício 1.
- Use a função loc para selecionar e imprimir a coluna "Nome" de todos os alunos.

*Exercício 4: Utilizando a função iloc para Selecionar Colunas por Índice Numérico*

- Utilize o DataFrame "dados_alunos" criado no exercício 1.
- Use a função iloc para selecionar e imprimir a coluna de índice 1 (ou seja, a segunda coluna).

*Exercício 5: Utilizando a função loc para Selecionar Linhas e Colunas por Rótulo*

- Utilize o DataFrame "dados_alunos" criado no exercício 1.
- Use a função loc para selecionar e imprimir a idade do aluno com índice "C".

*Exercício 6: Utilizando a função iloc para Selecionar Linhas e Colunas por Índice Numérico*

Utilize o DataFrame "dados_alunos" criado no exercício 1.
Use a função iloc para selecionar e imprimir a idade do aluno na primeira linha e segunda coluna.

<div>
<p ><img  align="right" src="https://res.cloudinary.com/crunchbase-production/image/upload/c_lpad,h_256,w_256,f_auto,q_auto:eco,dpr_1/aj29iemt0ogdyrdlksd4" height="160px"></p>
</div>

<br>
<br>

# **06 - Agrupamento e Ordenação**

<br>
<br>

___

*Exercício 1: Utilizando a função groupby*

- Importe a biblioteca pandas.
- Crie um DataFrame chamado "dados_vendas" com as colunas "Produto", "Vendedor" e "Valor".
- Preencha o DataFrame com dados fictícios de vendas.
- Use a função groupby para agrupar as vendas por vendedor e calcular o total de vendas de cada vendedor.
- Imprima o resultado.

*Exercício 2: Utilizando a função sort_values para Classificar os Dados*

- Utilize o DataFrame "dados_vendas" criado no exercício 1.
- Use a função sort_values para classificar as vendas em ordem decrescente com base no valor.
- Imprima o DataFrame após a classificação.

*Exercício 3: Utilizando a função groupby com Classificação*

- Utilize o DataFrame "dados_vendas" criado no exercício 1.
- Use a função groupby para agrupar as vendas por produto e, em seguida, use a função sort_values para classificar as vendas de cada produto em ordem crescente com base no valor.
- Imprima o resultado.

*Exercício 4: Utilizando a função groupby com Classificação Personalizada*

- Utilize o DataFrame "dados_vendas" criado no exercício 1.
- Use a função groupby para agrupar as vendas por vendedor e, em seguida, use a função sort_values para classificar as vendas de cada vendedor em ordem decrescente com base no valor.
- Imprima o resultado.

<div>
<p ><img  align="right" src="https://res.cloudinary.com/crunchbase-production/image/upload/c_lpad,h_256,w_256,f_auto,q_auto:eco,dpr_1/aj29iemt0ogdyrdlksd4" height="160px"></p>
</div>

<br>
<br>

# **07 - Combinando Dados**

<br>
<br>

___

*Exercício 1: Utilizando a função concat para Juntar DataFrames Verticalmente*

- Importe a biblioteca pandas.
- Crie dois DataFrames, "dados1" e "dados2", com colunas "Nome" e "Idade".
- Preencha os DataFrames com dados fictícios.
Utilize a função concat para juntar os DataFrames verticalmente (um abaixo do outro) e imprima o resultado.

*Exercício 2: Utilizando a função concat para Juntar DataFrames Horizontalmente*

- Utilize os DataFrames "dados1" e "dados2" criados no exercício anterior.
- Use a função concat para juntar os DataFrames horizontalmente (um ao lado do outro) e imprima o resultado.

*Exercício 3: Utilizando a função merge para Mesclar DataFrames por Coluna Comum*

- Crie dois DataFrames, "vendedores" e "vendas", com informações sobre vendedores e suas vendas, respectivamente.
- Use a função merge para mesclar os DataFrames com base na coluna comum "ID" e imprima o resultado.

*Exercício 4: Utilizando a função merge com Mescla Interna e Colunas Diferentes*

- Utilize os DataFrames "vendedores" e "vendas" criados no exercício anterior.
- Use a função merge para mesclar os DataFrames com base em colunas diferentes ("ID" em "vendedores" e "Vendedor_ID" em "vendas").
- Imprima o resultado da mescla.

*Exercício 5: Utilizando a função join para Unir DataFrames por Índice*

- Importe a biblioteca pandas.
- Crie dois DataFrames, "alunos" e "notas", com informações sobre alunos e suas notas, respectivamente.
- Use a função set_index para definir o índice de ambos os DataFrames como a coluna "ID".
- Utilize a função join para unir os DataFrames por índice e imprima o resultado.

<div>
<p ><img  align="right" src="https://res.cloudinary.com/crunchbase-production/image/upload/c_lpad,h_256,w_256,f_auto,q_auto:eco,dpr_1/aj29iemt0ogdyrdlksd4" height="160px"></p>
</div>

<br>
<br>

# **08 - Substituindo Dados**

<br>
<br>

___

*Exercício 1: Utilizando a função replace para Substituir Valores*

- Utilize o DataFrame "dados_alunos" criado no exercício 1.
- Use a função replace para substituir a idade "30" por "31" no DataFrame.
- Imprima o DataFrame após a substituição.

*Exercício 2: Utilizando a função replace com Dicionário de Substituição*

- Utilize o DataFrame "dados_alunos" criado no exercício 1.
- Crie um dicionário de substituição onde a idade "25" é substituída por "26" e a idade "35" é substituída por "36".
- Use a função replace com o dicionário de substituição para atualizar as idades.
- Imprima o DataFrame após a atualização.

<div>
<p ><img  align="right" src="https://res.cloudinary.com/crunchbase-production/image/upload/c_lpad,h_256,w_256,f_auto,q_auto:eco,dpr_1/aj29iemt0ogdyrdlksd4" height="160px"></p>
</div>

<br>
<br>

# **09 - Gráficos com Pandas**
<br>
<br>

___

*Exercício 1: Gráficos*

Carregue um CSV/EXCEL que você já utiliza no seu trabalho e crie um gráfico com pandas de cada tipo:
- barras
- dispersão
- histograma
- linha
- box